---
AWSTemplateFormatVersion: 2010-09-09
Description: 'Usage Report Notification'

Resources:
  UsageReportS3:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete
    Properties:
      BucketName: "{{resolve:ssm:/usage-report/s3/backup-bucket:1}}"
      LifecycleConfiguration:
        Rules:
          - Id: BackupRetention
            ExpirationInDays: 14
            Status: Enabled

  UsageReportS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref UsageReportS3
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref UsageReportS3
                - /*
            Principal: '*'

  UsageReportLambdaRole01:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
          Action:
            - sts:AssumeRole
      Path: "/"
  
  UsageReportLambdaPolicies01:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'sts:*'
              - 'ce:*'
              - 'ssm:*'
              - 'ses:*'
              - 'sns:*'
              - 'cloudwatch:*'
              - 'logs:*'
              - 's3:*'
            Resource: '*'
      Roles:
        - !Ref UsageReportLambdaRole01

  UsageReportTopic01:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: usage-report-topic
      TopicName: usage-report-topic
      Subscription:
      - Endpoint: "{{resolve:ssm:/usage-report/email/usage-destination-address}}"
        Protocol: email

  UsageReportTopic01Arn:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "/usage-report/topic/arn"
      Type: "String"
      Value: !Ref UsageReportTopic01
    DependsOn: UsageReportTopic01

  SNScodebuildLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: Usage Report
      Runtime: python3.9
      Timeout: 10
      Handler: index.lambda_handler
      Role: !GetAtt UsageReportLambdaRole01.Arn
      Environment:
        Variables:
          aws_accounts: "{{resolve:ssm:/usage-report/accounts/list}}"
          asumerole_name: "{{resolve:ssm:/usage-report/accounts/asumerole}}"
          primary_region: "{{resolve:ssm:/usage-report/accounts/region}}"
      Code:
        ZipFile:
          !Sub
            - |-

            - lambda_function_role_arn: !Ref UsageReportLambdaRole01
    DependsOn: UsageReportTopic01Arn